branches:
  only:
    - master

sudo: false
language: node_js
node_js:
  - "8"
  - "6"

if: tag IS blank

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

matrix:
  include:
    - env: NAME="test"
      install: true
      script:
        - yarn test
        - yarn run codecov

    - env: NAME="integration test"
      install: true
      script:
        - yarn test:example

    - env: NAME="deploy"
      script:
        - npm pack
      after_success:
        - npm install -g @zeus-ci/cli
        - zeus upload -t "application/tar+npm" *.tgz

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/ad511932-ca25-11e7-a96d-0a580a280309/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
