name: build

on:
  push:
    branches:
      - master
      - release/**

env:
  NODE_OPTIONS: '--stack-trace-limit=10000'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: yarn install
      - run: yarn pack
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/*.tgz
